###############################################################
# appspec.yml — Đặt ở ROOT của GitHub repository
# CodeDeploy ECS đọc file này để thực hiện Blue/Green deployment
###############################################################
version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "frontend"
          ContainerPort: 3000
        # Sau khi Green healthy, giữ Blue thêm 5 phút rồi terminate
        PlatformVersion: "LATEST"
